learning_users/basic_app/urls.py
from django.conf.urls import url
from basic_app import views


#template url
app_name = 'basic_app'

urlpatterns=[

    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),


]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from basic_app import views

urlpatterns = [
    path('',views.index, name='index'),
    path('basic_app/',include('basic_app.urls')),
    path('admin/', admin.site.urls),
    url(r'^logout/$',views.user_logout, name='logout'),
    url(r'^special/$',views.special, name='special'),
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.DO_NOTHING)  #inherit from user call where first name last name is automatically imported


    #additional classs
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank=True)   #profile pics folder in media

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required




# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def special(request):
    return HttpResponse("Your logined in")


@login_required     #17 th line requires login required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)
        if user_form.is_valid() and profile_form.is_valid():



            user = user_form.save()
            user.set_password(user.password)   #encrypt password
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user        #one to one relationship


            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']


            profile.save()


            registered = True
        else:
            print(user_form.errors, profile_form)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basic_app/registration.html',                          #DTL tags in registration.html
                                    {'user_form':user_form,
                                        'profile_form':profile_form,
                                            'registered':registered})












def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')     #input name username
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)   #authenticate code
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Account not active")
        else:
            print("someone failed to login")
            print("username : {} and password {}".format(username, password))
            return HttpResponse("invalid login")
    else:
        return render(request,'basic_app/login.html',{})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>


  </head>
  <body>
      <nav>
         <div class="container">
            <ul>
                <li> <a href="{% url 'index' %}">DJANGO</a></li>
                <li> <a href="{% url 'admin:index' %}">ADMIN</a></li>
                <li> <a href="{% url 'basic_app:register' %}">REGISTER</a></li>

                {% if user.is_authenticated %}
                <li> <a href="{% url 'logout' %}">LOGOUT</a> </li>

                {% else %}
                <li> <a href="{% url 'basic_app:user_login' %}">LOGIN</a> </li>

                {% endif %}
            </ul>
         </div>
      </nav>

      <div class="container">

        {% block body_block %}
        {% endblock %}
      </div>



  </body>
</html>

learning_users/templates/basic_app/index.html
{% extends  "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>Django</h1>
</div>

{% endblock %}

learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block%}


<div class="jumbotron">

  <h1>plz login</h1>
  <form action="{% url 'basic_app:user_login' %}" method="post">

    {% csrf_token %}
    <label for="username">username: </label>
    <input type="text" name="username" placeholder="enter user name">


    <label for="password">password: </label>
    <input type="password" name="password" placeholder="enter password">


    <input type="submit" name="" value="login">

  </form>

</div>

{% endblock %}

learning_users/templates/basic_app/registration.html
{% extends  "basic_app/base.html" %}
{% load static %}
{% block body_block %}

<div class="jumbotron">
  {% if registered %}

    <h1>Thanks</h1>

  {% else %}
    <h1>Register here</h1>
    <h3>Fill out</h3>

    <form method="POST" enctype="multipart/form-data">

      {% csrf_token %}
      {{user_form.as_p}}
      {{profile_form.as_p}}
      <input type="submit" name="" value="REGISTER">

    </form>


  {% endif%}



</div>

{% endblock %}